ui_webapp/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views 
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('signup/',views.signup, name='signup'),
    path('logout/',auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('login/', auth_views.LoginView.as_view(next_page='/',template_name='core/login.html', authentication_form=LoginForm), name='login')
]

ui_webapp/imdb/urls.py
from django.urls import path 

from .views import * 

app_name = 'imdb'

urlpatterns = [
    path('movies/<int:id_movie>',get_one_movie, name='one_movie'),
    path('movies',get_movies,name='all_movies'),
    path('actors/<int:actor_id>',get_one_actor, name='one_actor'),
    path('actors/',get_actors,name='all_actors'),
    path('directors/<int:actor_id>',get_one_director, name='one_directors'),
    path('directors/',get_directors,name='all_directors'),
    path('genres/<int:actor_id>',get_one_genre, name='one_genre'),
    path('genres/',get_genres,name='all_genres'),
    path('rec/',get_recommendations,name='get_rec'),
    path('rec/desc',get_recommendations_by_desc,name='get_rec_by_desc'),
    path('', home, name='home')
]

ui_webapp/movie_webapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('imdb.urls')),
    path('',include('core.urls'))
]

ui_webapp/imdb/models.py
from django.db import models

class Movie(models.Model):

    id_movie = models.AutoField(primary_key=True)
    titre = models.CharField(max_length=256, blank=True, null=True)
    img_url = models.CharField(max_length=256, blank=True, null=True)
    desc_fr = models.TextField(blank=True, null=True)
    desc_en = models.TextField(blank=True, null=True)
    anecdote = models.TextField(blank=True, null=True)
    rating_content = models.CharField(max_length=256, blank=True, null=True)
    year = models.CharField(max_length=256, blank=True, null=True)
    imdb_int = models.IntegerField(blank=True, null=True)
    rating_count = models.IntegerField(blank=True, null=True)
    recommendation_rate = None

    actors_matching = models.ManyToManyField(
        'Actor',
        through = 'ActorsMovies',

    )

    directors_matching = models.ManyToManyField(
        'Director',
        through = 'DirectorsMovies',

    )

    genres_matching = models.ManyToManyField(
        'Genre',
        through = 'GenresMovies',
    )

    @property
    def actors(self):

        actors_list = self.actors_matching.all()

        

        serializable_actors = [
            {
                "id":actor.id,
                "name":actor.name
            }
            for actor in actors_list
        ]
        return serializable_actors

    @property
    def directors(self):

        directors_list = self.directors_matching.all()

        serializable_directors = [
            {
                "id":director.id,
                "name":director.name
            }
            for director in directors_list
        ]
        return serializable_directors
    
    @property
    def genres(self):

        genres_list = self.genres_matching.all()

        serializable_genres = [
            {
                "id":genre.id,
                "name":genre.name
            }
            for genre in genres_list
        ]
        return serializable_genres
    
    class Meta:
        managed = False
        db_table = 'movies'
    
    def set_rec_rate(self,rate:float):
        self.recommendation_rate = rate

    def __str__(self) -> str:
        return self.titre


class Actor(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=256)
    firstname = models.CharField(blank=True, null=True)
    lastname = models.CharField(blank=True, null=True)
    movies_matching = models.ManyToManyField(
        'Movie',
        through = 'ActorsMovies',

    )

    @property
    def movies(self):

        movies_list = self.movies_matching.all()

        serializable_movies = [
            {
                "id":movie.id_movie,
                "titre":movie.titre,
                "img_url":movie.img_url
            }
            for movie in movies_list
        ]
        return movies_list

    class Meta:
        managed = False
        db_table = 'actors'
    
    def __str__(self):
        return f"{self.firstname} {self.lastname}"


class ActorsMovies(models.Model):
    imdb_id = models.CharField(max_length=256)
    actor = models.ForeignKey(Actor, models.DO_NOTHING)
    movies = models.ForeignKey(Movie, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'actors_movies'


class Director(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=256)
    firstname = models.CharField(blank=True, null=True)
    lastname = models.CharField(blank=True, null=True)
    movies_matching = models.ManyToManyField(
        'Movie',
        through = 'DirectorsMovies',

    )

    @property
    def movies(self):

        movies_list = self.movies_matching.all()

        serializable_movies = [
            {
                "id":movie.id_movie,
                "titre":movie.titre,
                "img_url":movie.img_url
            }
            for movie in movies_list
        ]
        return movies_list

    class Meta:
        managed = False
        db_table = 'directors'
    
    def __str__(self):
        return f"{self.firstname} {self.lastname}"


class DirectorsMovies(models.Model):
    imdb_id = models.CharField(max_length=256)
    director = models.ForeignKey(Director, models.DO_NOTHING)
    movies = models.ForeignKey(Movie, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'directors_movies'


class Genre(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=256)
    movies_matching = models.ManyToManyField(
        'Movie',
        through = 'GenresMovies',

    )

    @property
    def movies(self):

        movies_list = self.movies_matching.all()

        serializable_movies = [
            {
                "id":movie.id_movie,
                "titre":movie.titre,
                "img_url":movie.img_url
            }
            for movie in movies_list
        ]
        return movies_list

    class Meta:
        managed = False
        db_table = 'genres'
    
    def __str__(self):
        return self.name


class GenresMovies(models.Model):
    
    genre = models.ForeignKey(Genre, models.DO_NOTHING)
    imdb_id = models.CharField(max_length=256)
    movies = models.ForeignKey(Movie, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'genres_movies'




class Scenarist(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=256)
    firstname = models.CharField(blank=True, null=True)
    lastname = models.CharField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'scenarists'
    
    def __str__(self):
        return f"{self.firstname} {self.lastname}"


class ScenaristsMovies(models.Model):
    imdb_id = models.CharField(max_length=256)
    scenarist = models.ForeignKey(Scenarist, models.DO_NOTHING)
    movies = models.ForeignKey(Movie, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'scenarists_movies'

ui_webapp/imdb/forms.py
from django import forms

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border mt-4'

class RecommendationForm(forms.Form):
    titles = forms.CharField(label="Type your title here :", 
                                max_length=100, 
                                required=True, 
                                widget=forms.TextInput(
                                    attrs={
                                        'placeholder': 'Dogville', 
                                        'class': INPUT_CLASSES}))
    
class InferenceForm(forms.Form):
    description = forms.CharField(label="Type the description of the movie you would want to watch :", 
                                max_length=128, 
                                required=True, 
                                widget=forms.TextInput(
                                    attrs={
                                        'placeholder': 'Type your description here ...', 
                                        'class': INPUT_CLASSES}))

ui_webapp/imdb/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_protect
from .models import *
from django.db import connection
from django.core.paginator import Paginator
import requests, json
from .forms import RecommendationForm, InferenceForm
from .recom import request_recommendation, parse_recommendation

#---HOME--------------------------------------------------------------------------------------------------------------

@csrf_protect
@require_http_methods(["GET"])
def home(request):

    # id for the home page
    ids = [32994, 38683, 37341,33907]
    movies = []
    for id_movie in ids:
        movie = Movie.objects.filter(id_movie=id_movie)
        movies.append(movie[0])

    # actor for the home page 
    ids = [1357, 1183, 1803, 1442]
    actors = []
    for id_actor in ids:
        actor = Actor.objects.filter(id=id_actor)
        actors.append(actor[0])

    return render(
        request,
        'imdb/home.html',
        {
            'movies':movies,
            'actors':actors

        }
    )

#---RECOMMENDATIONS---------------------------------------------------------------------------------------------------

#---1. BY TITLE ---
@csrf_protect
@login_required(login_url='/login')
@require_http_methods(["POST","GET"])
def get_recommendations(request):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = RecommendationForm(request.POST)

        # whether the title is in the list or not
        # check whether it's valid:
        if form.is_valid():
 
            data_dic = json.loads(requests.post(url="http://localhost:8000/imdb/rec/",json=form.cleaned_data).text)

            # if movie requested not in db
            if data_dic['results'][0]['Recommendations'][0]['Rec_1']['title']== 'unknown_title':
                notinlist=True
                # redirects it to default page
                return render(request,'imdb/get_rec.html', {
                    'notinlist':notinlist,
                    'form':form
                }) 
            
            
            
            movie_form = Movie.objects.get(titre=form.cleaned_data['titles'])

            
            # getting imdb id from those films
            imdb_ids = []
            taux_recs = []
            
            j = 0
            i = 1
            while j < 5:
                
                imdb_id = data_dic['results'][0]['Recommendations'][j]['Rec_'+str(i)]['imdb_id']
                imdb_ids.append(imdb_id)
                taux_rec = data_dic['results'][0]['Recommendations'][j]['Rec_'+str(i)]['rec rate']
                taux_recs.append(taux_rec)
                i+=1
                j+=1

            movies = []

            i = 0
            for rec_imdb_id in imdb_ids:
                movie = Movie.objects.get(imdb_int=rec_imdb_id)
                movie.set_rec_rate(taux_recs[i])
                movies.append(movie)
                i+=1

            


            return render(request,
                          "imdb/display_rec.html", 
                          {"recommendations" :data_dic, 
                           'movie_form':movie_form,
                           'movies':movies,
                           'taux_recs':taux_recs,
                           })

    # if a GET (or any other method) we'll create a blank form
    else:
        form = RecommendationForm()

    return render(request, "imdb/get_rec.html", {"form": form})

#---2. BY DESC ---
@csrf_protect
@login_required(login_url='/login')
@require_http_methods(["POST","GET"])
def get_recommendations_by_desc(request):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = InferenceForm(request.POST)

        # whether the title is in the list or not
        # check whether it's valid:
        if form.is_valid():

            data_dic = json.loads(requests.post(url="http://localhost:8000/imdb/rec/desc",json=form.cleaned_data).text)
                                 
            # getting imdb id from those films
            imdb_ids = []
            taux_recs = []
            
            j = 0
            i = 1
            while j < 5:
                
                imdb_id = data_dic['results'][0]['Recommendations'][j]['Rec_'+str(i)]['imdb_id']
                imdb_ids.append(imdb_id)
                taux_rec = data_dic['results'][0]['Recommendations'][j]['Rec_'+str(i)]['rec rate']
                taux_recs.append(taux_rec)
                i+=1
                j+=1

            movies = []

            i = 0
            for rec_imdb_id in imdb_ids:
                movie = Movie.objects.get(imdb_int=rec_imdb_id)
                movie.set_rec_rate(taux_recs[i])
                movies.append(movie)
                i+=1

            


            return render(request,
                          "imdb/display_rec.html", 
                          {"recommendations" :data_dic, 
                           'movies':movies,
                           'taux_recs':taux_recs,
                           })

    # if a GET (or any other method) we'll create a blank form
    else:
        form = InferenceForm()

    return render(request, "imdb/get_rec.html", {"form": form})
    

#---MOVIES------------------------------------------------------------------------------------------------------------

@csrf_protect
@require_http_methods(["GET"])
@login_required(login_url='/login')
def get_one_movie(request,id_movie):

    movie = get_object_or_404(Movie,id_movie=id_movie)

    title_type_list = {"titles":movie.titre}

    data_dic = request_recommendation(title_type_list)

    movies_recom = parse_recommendation(data_dic)


    # print(movies)
    return render(
        request,
        'imdb/movie.html',
        {
            'movie':movie,
            'movies_recom':movies_recom
        }
    )

@csrf_protect
@require_http_methods(["GET"])
@login_required(login_url='/login')
def get_movies(request):
    movies = Movie.objects.all()
    return render(
        request,
        'imdb/movies.html',
        {
            'movies':movies
        }
    )

#---ACTORS------------------------------------------------------------------------------------------------------------------

@csrf_protect
@require_http_methods(["GET"])
@login_required(login_url='/login')
def get_one_actor(request,actor_id):
    # DISPLAY ALL THE FILM THE ACTOR HAS PLAYED IN 
    actor = get_object_or_404(Actor,id=actor_id)

    actor_movies = actor.movies
    return render(request,
                  'imdb/actor.html',
                  {'actor':actor})


@csrf_protect
@require_http_methods(["GET"])
@login_required(login_url='/login')
def get_actors(request):
    actors = Actor.objects.all()
    return render(
        request,
        'imdb/actors.html',
        {
            'actors':actors
        }
    )

#---DIRECTORS------------------------------------------------------------------------------------------------------------

@csrf_protect
@require_http_methods(["GET"])
@login_required(login_url='/login')
def get_one_director(request,actor_id):
    # TO EDIT : DISPLAY ALL THE FILM DIRECTED BY IT
    director = get_object_or_404(Director,id=actor_id)
    director_movies = director.movies

    return render(request,
                  'imdb/director.html',
                  {
                      'director':director
                  })

@csrf_protect
@require_http_methods(["GET"])
@login_required(login_url='/login')
def get_directors(request):
    directors = Director.objects.all()
    return render(
        request,
        'imdb/directors.html',
        {
            'directors':directors
        }
    )

#---GENRES----------------------------------------------------------------------------------------------------------------

@csrf_protect
@require_http_methods(["GET"])
@login_required(login_url='/login')
def get_one_genre(request,actor_id):
    #TO EDIT : display all the films that has the genre
    genre = get_object_or_404(Genre,id=actor_id)

    movies_p = Paginator(genre.movies,20)
    return render(request,
                  'imdb/genre.html',
                  {
                      'genre':genre,
                      'movies' : movies_p.page(1).object_list,
                  })

@csrf_protect
@require_http_methods(["GET"])
@login_required(login_url='/login')
def get_genres(request):
    genres = Genre.objects.all()
    return render(
        request,
        'imdb/genres.html',
        {
            'genres':genres
        }
    )

ui_webapp/imdb/templates/imdb/actor.html
{% extends 'imdb/base.html' %}
{% load static %}
{% block title %} {{ actor }} {% endblock %}
{% block content %}
<div class="p-6 flex flex-col items-center ">
    <div class="w-3/4">
        <a href="/movies/{{actor.id}}" class="text-center text-3xl font-semibold "> {{ actor }} </a>
        <div class="flex">
            <div class="w-1/2 p-10">
                <img src="{% static 'imdb/images/user.png' %}" alt="" class="p-10">
                <h2 class="mt-10"> Informations personnelles : </h2>

            </div>
            <ul class="w-1/2 wrapper-2">
            {% for movie in actor.movies %}
                <li class="mt-6 py-4 px-6 bg-neutral-200  rounded-xl">
                    <a href="/movies/{{movie.id_movie}}" class="mt-2 text-center"> 
                        <img src="{{ movie.img_url}}" alt="poster of the movie" class="rounded-xl">
                    </a>
                    <div class="flex flex-col justify-center">
                        <a href="/movies/{{movie.id_movie}}" class="mt-2 text-center font-semibold"> {{ movie.titre }}</a> 
                        <p class="text-center mt-2">({{movie.year}})</p>
                    </div>
                    
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

ui_webapp/imdb/templates/imdb/actors.html
{% extends 'imdb/base.html' %}
{% block title %} actor name {% endblock %}
{% block content %}
<div class="p-6 flex flex-col items-center ">

</div>
{% endblock %}

ui_webapp/imdb/templates/imdb/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <link  href="{% static 'imdb/styles.css' %}" rel="stylesheet">
        <title>{% block title %}{% endblock %} | Le dernier métro </title>

    </head>
    <body>
        <nav class="py-6 px-6 flex  items-center border-b border-grey-200 bg-white">
            <div class="flex justify-between  w-2/3 pr-20">
                <a href="/" class="text-3xl font-semibold">
                    <img src="{% static 'imdb/images/icon.png' %}" alt="Logo" class="object-scale-down w-16 rounded-xl">
                </a>
                <a href="/" class="text-4xl font-semibold mt-2 ml-6 "> Le dernier metro </a>
            </div>
            <div class="space-x-2 w-1/3 flex justify-end">
                {% if request.user.is_authenticated %}
                <a href="#" class="text-center w-1/4 py-3 text-lg font-semibold hover:text-gray-500 "> Browse </a>
                <a href="#" class=" text-center w-1/4 px-2 py-3 text-lg font-semibold bg-amber-500 text-white rounded-xl hover:bg-amber-700"> Dashboard </a>
                <a href="#" class="text-center w-1/4 px-3 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-amber-700"> Settings</a>
                <a href="{% url 'core:logout' %}" class="text-center w-1/4 px-3 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-red-700"> Logout</a>
                {% else %}
                <a href="#" class="text-center px-5 py-3 w-1/3 text-lg font-semibold hover:text-gray-500"> Browse </a>
                <a href="{% url 'core:signup' %}" class="text-center px-6 py-3 text-lg font-semibold bg-amber-500 text-white rounded-xl hover:bg-amber-700"> Sign up</a>
                <a href="{% url 'core:login' %}" class="text-center px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-amber-700"> Log in </a>
                {% endif %}
            </div>
        </nav>
        <div class="px-6 py-6 min-h-screen flex flex-col items-center">
            {% block content %}
            {% endblock %}
        </div>
        <footer class="py-6 px-6 flex justify-between bg-gray-800 ">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400"> About </h3>

                <p class="text-lg text-gray-500">Lorem ipsum dolor sit amet consectetur adipisicing elit. A ea quibusdam nemo ipsam consectetur odio. 
                    Ratione magnam exercitationem enim. Dignissimos cumque non reprehenderit odio qui aliquid, laborum incidunt architecto tenetur.</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400"> Menu </h3>
                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-amber-500 hover:text-amber-700">About</a></li>
                    <li><a href="#" class="text-lg text-amber-500 hover:text-amber-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-amber-500 hover:text-amber-700">Privacy</a></li>
                    <li><a href="#" class="text-lg text-amber-500 hover:text-amber-700">Terms of use</a></li>
                </ul>
            </div>

        </footer>
    </body>
    {% block extra_body %}
    {% endblock %}
</html>

ui_webapp/imdb/templates/imdb/director.html
{% extends 'imdb/base.html' %}
{% load static %}
{% block title %} {{ director }}{% endblock %}
{% block content %}
<div class="p-6 flex flex-col items-center ">
    <div class="w-3/4">
        <a href="/movies/{{director.id}}" class="text-center text-3xl font-semibold "> {{ director }}</a>
        <div class="flex">
            <div class="w-1/2 p-10">
                <img src="{% static 'imdb/images/user.png' %}" alt="" class="p-10">
                <h2 class="mt-10"> Informations personnelles : </h2>

            </div>
            <ul class="w-1/2 wrapper-2">
            {% for movie in director.movies %}
                <li class="mt-6 py-4 px-6 bg-neutral-200  rounded-xl">
                    <a href="/movies/{{movie.id_movie}}" class="mt-2 text-center"> 
                        <img src="{{ movie.img_url}}" alt="poster of the movie" class="rounded-xl">
                    </a>
                    <div class="flex flex-col justify-center">
                        <a href="/movies/{{movie.id_movie}}" class="mt-2 text-center font-semibold"> {{ movie.titre }}</a> 
                        <p class="text-center mt-2">({{movie.year}})</p>
                    </div>
                    
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

ui_webapp/imdb/templates/imdb/directors.html
{% extends 'imdb/base.html' %}
{% block title %} actor name {% endblock %}
{% block content %}
<div class="p-6 flex flex-col items-center ">

</div>
{% endblock %}

ui_webapp/imdb/templates/imdb/display_rec.html
{% extends 'imdb/base.html' %}
{% block title %} Results {% endblock %}
{% block content %}
<div class="p-6 flex flex-col items-center w-5/6">
    <a href="/movies/{{movie_form.id_movie}}" class="text-3xl"> {{ movie_form }} </a>
    <div class="flex">
        {% for movie in movies %}
        <div class="border-amber-300 border-2 rounded-xl p-10 mt-10 ml-5 w-1/5 flex flex-col justify-between">
            
            <a href="/movies/{{movie.id_movie}}"  class="w-full">
                <img src="{{ movie.img_url}}" alt="poster of the movie rounded-xl" class=" rounded-xl">
            </a>
            <div class="justify-end">
                <div class="flex justify-center">
                    <a href="/movies/{{movie.id_movie}}" class="text-center mt-5 font-bold mt-6 py-4 px-6 bg-amber-500 hover:bg-amber-700 rounded-xl"> {{ movie.titre }}</a>
                </div>
                <div class="flex mt-5 justify-center">
                    <p class="">Recommendé à :</p>
                    <p class="ml-5"> {{ movie.recommendation_rate}} (%)</p>
                </div>
            </div>
            <!-- <div>
                
                {% for genre in movie.genres %}
                
                <div>
                    <a href="/genres/{{genre.id}}" class="mt-6 py-4 px-6 bg-amber-500 hover:bg-amber-700 rounded-xl">{{ genre.name }}</a>
                </div>
                {% endfor %}
            </div>  -->
            <!--
            <div>
                
                {% for actor in movie.actors %}
                
                <div>
                    <a href="/actors/{{actor.id}}">{{ actor.name }}</a>
                </div>
                {% endfor %}
            </div>
            <div>
                
                {% for director in movie.directors %}
                
                <div>
                    <a href="/directors/{{director.id}}">{{ director.name }}</a>
                </div>
                {% endfor %}
            </div> -->
        </div>
        {% endfor %}


    </div>
    
    
</div>
{% endblock %}

ui_webapp/imdb/templates/imdb/genre.html
{% extends 'imdb/base.html' %}
{% block title %} {{ genre }}{% endblock %}
{% block content %}
<div class="p-6 flex flex-col items-center ">
    <div class="w-3/4">
        <a href="/movies/{{director.id}}" class="text-center text-3xl font-semibold "> {{ genre }}</a>
        <div class="">
            <ul class="wrapper-4">
            {% for movie in movies %}
                <li class="mt-6 py-4 px-6 bg-neutral-200  rounded-xl ">
                    <a href="/movies/{{movie.id_movie}}" class="mt-2 text-center"> 
                        <img src="{{ movie.img_url}}" alt="poster of the movie" class="rounded-xl">
                    </a>
                    <div class="flex flex-col justify-center">
                        <a href="/movies/{{movie.id_movie}}" class="mt-2 text-center font-semibold"> {{ movie.titre }}</a> 
                        <p class="text-center mt-2">({{movie.year}})</p>
                    </div>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

ui_webapp/imdb/templates/imdb/genres.html
{% extends 'imdb/base.html' %}
{% block title %} Genres {% endblock %}
{% block content %}
<div class="p-6 flex flex-col items-center ">
    
</div>
{% endblock %}

ui_webapp/imdb/templates/imdb/home.html
{% extends 'imdb/base.html' %}
{% load static %}
{% block title %}  {% endblock %}
{% block content %}
<div class="p-6 flex flex-col items-center w-5/6">
    <h1 class="text-xl">Bienvenue à bord du Dernier Métro ! </h1>

    <div class="flex justify-around mt-10">
        {% if request.user.is_authenticated %}
        <div class="p-5 rounded-xl border-amber-200 border-2 w-1/3">
            <a href="/rec" class="">
                <h1 class=" p-5 underline border-b-2 border-black text-center"> Moteurs de Recommandations </h1>
                <div class="flex justify-center w-full">
                    <button class=" px-3 py-5 font-semibold mt-5 border-2 border-black  w-full rounded-xl hover:bg-neutral-200"> Moteur 1</button>
                </div>
                <a href="{% url 'imdb:get_rec_by_desc' %}" class="flex justify-center w-full">
                    <button class=" px-3 py-5 font-semibold mt-5 border-2 border-black  w-full rounded-xl hover:bg-neutral-200"> Moteur 2</button>
                </a>
                <div class=" flex flex-col justify-around">
                    <p class=" pt-5">
                        En encodant les phrases de mots avec le modèle BERT, notre moteur de recommandation permet pour chaque description de film de l'associer à la description d'un autre le film le plus proche spatialement !
                        Modèle small-bert-uncased , poids téléchargé sur huggingface.co . 
                    </p>
                    <div class="h-1/4 mt-10">
                        <img src="{% static 'imdb/images/transformer.png'%}" alt="" class="rounded-xl">
                    </div>
                </div>
            </a>
        </div>
        <div class="p-5 rounded-xl border-amber-200 border-2 w-1/3 ml-10">
            <h1 class=" border-b-2 border-black p-5 underline text-center"> Notre Liste de Films </h1>
            <div class="wrapper-2">
            {% for movie in movies %}
                <div class="mt-6 py-4 px-6 bg-neutral-200  rounded-xl ">
                    <a href="/movies/{{movie.id_movie}}" class="mt-2 text-center w-full"> 
                        <img src="{{ movie.img_url}}" alt="poster of the movie" class="rounded-xl mt-2 ">
                    </a>
                    <div class="flex flex-col justify-center">
                        <a href="/movies/{{movie.id_movie}}" class="mt-2 text-center font-semibold"> {{ movie.titre }}</a> 
                        <p class="text-center mt-2">({{movie.year}})</p>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
        <div class="p-5 rounded-xl  border-amber-200 border-2 w-1/3 ml-10">
            <h1 class="p-5 underline border-b-2 border-black text-center "> Notre Liste d'Acteurs </h1>
            <div class="wrapper-2 h-5/6">
                {% for actor in actors %}
                <div class="mt-6 py-4 px-6 bg-neutral-200  rounded-xl flex flex-col ">
                    <a href="/actors/{{actor.id }}" class="mt-2 text-center"> 
                        <img src="{% static 'imdb/images/user.png' %}" alt="" class="">
                    </a>
                    <div class="flex flex-col justify-end mt-2">
                        <a href="/actors/{{actor.id}}" class="mt-2 text-center font-semibold"> {{ actor }}</a> 
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </div>
    {% else %}
        <div class="min-h-screen">
            <h1>Pour accéder aux fonctionnalités du site, veuillez tout d'abord vous connecter :</h1>
            <div class=" flex justify-center">
                <a href="/login" class="py-4 px-8 text-lg bg-amber-500 hover:bg-amber-600 rounded-xl text-white mt-10 w-2/3 text-center font-semibold"> Login </a>
            </div>
        </div>
    {% endif%}
</div>
{% endblock %}

ui_webapp/imdb/templates/imdb/movies.html
{% extends 'imdb/base.html' %}
{% block title %} actor name {% endblock %}
{% block content %}
<div class="p-6 flex flex-col items-center ">
    
</div>
{% endblock %}